import { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { checkRateLimit } from "@/utils/checkRateLimit";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isRateLimited = await checkRateLimit("GET", 100, 60);
  if (isRateLimited) {
    return <h1>To many GET requests. Try again later.</h1>;
  }

  return (
    <html lang="en" className="h-full flex-center">
      <body className="h-full w-full flex-center">{children}</body>
    </html>
  );
}
